### ISSUE TITLE
Test still showing as passed and as a warning

### ISSUE THREAD

**Issue by bbrownchg** [PatchMyPCTeam/WSUS-Clippy#3]
I just installed this for the first time - great tool! I fixed a couple of small issues in my environment related to the app pool, but noticed that ping test shows as passed now but also still shows as a warning.

![image](https://user-images.githubusercontent.com/47155353/210400692-330adb20-a273-435f-a935-662a11fd4c05.png)

![image](https://user-images.githubusercontent.com/47155353/210400740-4bdc11ea-9f91-4ede-b303-1ae314beec67.png)

According to the release notes, v1.1.0.0 fixed an issue where changes weren't detected until the tool was closed and reopened. Once I closed the tool and reopened, however, the ping test no longer shows as a warning.

Let me know if there's any additional information I can provide.

**Comment by scotscottmca** [comment]
Thanks for pointing this out @bbrownchg! I've fixed that in code and will get it out as soon as possible :)

**Comment by scotscottmca** [comment]
fixed in https://github.com/PatchMyPCTeam/MEM-Patching-Optimizer/releases/tag/v1.1.5.0
