### ISSUE TITLE
Application cannot connect to WSUS DB

### ISSUE THREAD

**Issue by elc-cs** [PatchMyPCTeam/WSUS-Clippy#6]
The tool doesn't appear to connect to the SUSDB if it is on the same server as the MEM DB but in a different instance of MSSQL:
Encountered an error checking for nclLocalizedPropertyIDIndexes - System.Data.SqlClient.SqlException (0x80131904): Database 'SUSDB' does not exist. Make sure that the name is entered correctly.

Including the instance name in the option to specify the WSUS server does not appear to work. E.g. memserver.contoso.com\SCCMWSUS

Specifying the same server name works in SSMS. Running the tool on the server so no firewall between.

**Comment by elc-cs** [comment]
OK figured this out, the tool connects using tcp/ip. Adding a port to the instance and specifying the port works (support added following https://github.com/PatchMyPCTeam/MEM-Patching-Optimizer/issues/1). Perhaps one to add to the documentation?

**Comment by scotscottmca** [comment]
hey @elc-cs thanks for pointing this out! I think I know the problem, let me take a look at it and get back to you.

**Comment by Stonywall** [comment]
This seems to still be an issue.  Have you been able to investigate the connection problem?

**Comment by scotscottmca** [comment]
Hey @Stonywall @elc-cs my apologies, I've not had the greatest deal of time to focus on this recently as it's a side project. 

I'm working on it now though :) This should be fixed in the coming weeks.

**Comment by GbCaa** [comment]
I'm having the exact same issue. Thanks for taking care of it @smcallister594

**Comment by scotscottmca** [comment]
Hey @elc-cs @GbCaa can you confirm if the latest preview release resolves this issue?

**Comment by elc-cs** [comment]
> Hey @elc-cs @GbCaa can you confirm if the latest preview release resolves this issue?

Yep that seems to have sorted it thanks!

**Comment by scotscottmca** [comment]
Issue looks to be resolved in latest preview.
