### ISSUE TITLE
Unable to connect to remote WSUS without pre-reqs installed

### ISSUE THREAD

**Issue by Stonywall** [PatchMyPCTeam/WSUS-Clippy#7]
Computer without pre-reqs installed.

Application installs with no notice of missing pre-reqs.
Application starts, no errors or indication of missing dependencies.
Running the tests show two errors regarding connection issues to WSUS and then application closes without producing an error.
Log file is produced, with expected connection errors and stating missing pre-reqs.

Would be good if the application checked either before installing or before running.
Would also be good if the application provided a link to a how-to install the missing pre-reqs or links to download what is missing or automatically downloaded and installed them.

**Comment by scotscottmca** [comment]
Hey, remote connectivity to WSUS is not support. 

The expectation of this tool is that it is run directly on your WSUS server.
